### ISSUE TITLE
Create Github Repositories

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#11]
As a developer i can create new GitHub repositories for my project so that i am able to begin the project

### Task
- [x] Go to GitHub and create a new repository
- [x] Create separate repositories for Django and react
- [x] Enter a meaningful name for the repository
- [x] Create a project for the repository
- [x] Add in the user stories and epics
- [x] Break the user stories and epics into must, should, could and won’t have

### Acceptance criteria
- [x] Successfully create GitHub repository 
- [x] User stories, tasks and epics added
- [ ] Project successfully created
- [x] User stories given labels of must, should, could and won’t have
