### ISSUE TITLE
Deploy API

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#13]
As a developer i can deploy my API to Heroku so that I can use it in my front-end application and check all necessary tools and software is included in the site

### Task
- [ ] Sign in or create Heroku app
- [x] Link GitHub repository to Heroku.
- [x] Deploy the site to Heroku
- [ ] Update config vars
- [x] Access site through the browser

### Acceptance criteria
- [ ] The Heroku app is created
- [ ] The GitHub repository is linked with the Heroku app
- [ ] The site is successfully deployed to Heroku
- [ ] Config var has been updated.
- [x] Website appears in the browser using a json formatter.
