### ISSUE TITLE
Navigate Website Easily

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#14]
As a user I can easily find my way around the site so that I can access the different sections with no issues

### Task
- [x] Follow wireframe for website design.
- [ ] Create links with the same styling.
- [x] Create site using UX design principles 

### Acceptance criteria
- [ ] Wireframe has been followed in the design and layout.
- [x] Navigation bar has a set style across all pages
- [ ] Website has a consistent theme and styling across all pages
- [x] Correct font and colours have been used
