### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#16]
As a user I can find the about page so that I can learn more information about the site and how to use it

### Task
- [x] Create the component called “about”
- [ ] Add the component to the apps route file
- [x] Create the about page
- [ ] Link the about page to the route and correct URL address
- [x] Write content for page
- [ ] Make page responsive

### Acceptance criteria
- [x] You can access the about page from the navigation bar
- [ ] The about page shows the relevant information about the site
- [x] The about page loads when the correct URL is entered
- [ ] There is an about page created
- [x] The about page contains the correct information
