### ISSUE TITLE
Update Nav Bar Links

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#17]
As a developer I can update the nav bar links so that depending on the users access they will have certain links added to their nav bar 

### Task
- [x] Create a model for user accounts in the Django section of the project
- [x] Create a view for user authentication and authorisation
- [x] Create conditional functions in the react html  
- [x] Conditional functions to access user authority and display the result accordingly 

### Acceptance criteria
- [x] What appears on the navbar updates depending on the users log in access
- [ ] System correctly matches user log in with the access they should have
- [x] Navbar contains the correct links for the different pages
