### ISSUE TITLE
Breadcrumb Trail

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#18]
As a user, I can see a breadcrumb trail so that I understand my current location within the site and can easily navigate back.

### Task
- [x] Design and implement a breadcrumb component.
- [x] Ensure the breadcrumb trail is updated based what page the user is currently on.
- [ ] Style the breadcrumb to fit the site’s theme.

### Acceptance criteria
- [x] Breadcrumb trail is visible and accurate on relevant pages.
- [ ] Users can use the breadcrumb trail to navigate back to previous pages.
- [x] Breadcrumb fits with the theme of the website
