### ISSUE TITLE
Footer with links

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#19]
As a user, I can use the footer links so that I can navigate to important sections of the site.

### Task
- [x] Design and implement a footer with navigation links as per the wireframe.
- [x] Ensure the footer includes links to key sections similar to the header i.e home, about.

### Acceptance criteria
- [x] Footer is visible on all pages.
- [x] Footer contains links to key sections.
- [ ] Footer links are styled consistently and are functional.
- [x] Footer links take the user to the correct page
