### ISSUE TITLE
Search Wifi locations by country or city

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#20]
As a user, I can search for wifi locations by entering a continent, country or city name in the search bar, so that I can see all the results that relate to the search and I can view the different WIFI locations in a given city.

### Task
- [ ] Create a search bar in html
- [ ] Link search bar to database of wifi locations
- [ ] Add a submit button
- [ ] Add JavaScript eventlistener to listen for submission

### Acceptance criteria
- [ ] Search bar is visible on home page
- [ ] Search bar is large enough to show the full work typed
- [ ] Search bar is linked to database of WIFI locations
- [ ] Search bar has submit button
- [ ] Eventlistener attached to submit button
- [ ] If no result is returned the system informs the user
