### ISSUE TITLE
Continent Image Search

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#21]
As a user, I can search for WIFI spots by clicking on continent images, so that I can get a list of the different countries within that continent that have record.

### Task
- [x] get images for each of the continents
- [ ] Link the continents with countries in those continents
- [ ] Get generic image of continent with country name above it /overlay
- [x] Style continent images
- [x] Continent Images Interactive
- [x] Display Countries on Click

### Acceptance criteria
- [x] When a continent is clicked correct list of countries appear
- [x] Correct styling is added to continent image
- [ ] Continent image should be responsive depending on screen size
- [ ] Users can easily navigate through the image continents
