### ISSUE TITLE
Enter City Name

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#22]
As a user, I can enter a city name so that I get a list of results to see all wifi locations in that city.

### Task
- [ ] Implement a search feature
- [ ] Delay the search until the user has full entered the word
- [ ] Word is converted to lowercase when searched 
- [ ] Connect search bar to database
- [ ] Add in error handling
- [ ] Style results in keeping with the website theme

### Acceptance criteria
- [ ] Searching a city returns the correct result
- [ ] Search is not completed until the user has entered the full word
- [ ] Error handling catches all errors
- [ ] The correct styling is added
- [ ] If no results are found user is informed that no wifi locations exist
