### ISSUE TITLE
Search By Country Name

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#23]
As a user, I can search by country name so that I can see a list of cities within that country that have wifi locations recorded on the website.

### Task
- [x] Implement a search feature
- [x] Delay the search until the user has full entered the word
- [x] Word is converted to lowercase when searched 
- [x] Connect search bar to database
- [x] Add in error handling
- [x] Style results in keeping with the website theme

### Acceptance criteria
- [x] Searching a city returns the correct result
- [x] Search is not completed until the user has entered the full word
- [x] Error handling catches all errors
- [x] The correct styling is added
- [x] If no results are found user is informed that no WIFI locations exist
