### ISSUE TITLE
Filter by WIFI Rating

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#24]
As a user, I can filter the list of WIFI spots by their WIFI rating, so that I can find the locations with the best wifi signal and amenities that fit my search criteria.

### Task
- [ ] Create the wifi rating system
- [ ] Wifi rating should be shown as 5 stars
- [ ] Wifi rating is to be linked to each specific wifi location in the database value
- [ ] Create a rating system from 1-5, rating is calculated using total score divide by number of voters
- [ ] Create amenities icon for wifi listing 
- [ ] Amenities are shown on wifi location page
- [ ] Update the displayed list of WIFI locations based on the filter criteria
- [ ] Add in error handling 

### Acceptance criteria
- [ ] A list of icons representing amenities are added to the WIFI location page
- [ ] User can access the filter system
- [ ] Correct results are returned from the filter
- [ ] On screen message if no results match the filter request
- [ ] WIFI rating system works as expected and updates when a new user adds a new rating
