### ISSUE TITLE
No Result Found

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#25]
As a user after completing a search if there is no results I can see a button and be directed to a create a new listing so that after I have logged in or created an account I can create a new wifi location.

### Task
- [x] Create custom button
- [x] Write custom message to go with button
- [x] Style error message in keeping with the website design
- [x] Code an option for user to add in a new entry
- [x] Redirect users to a login or signup page if they are not logged in.

### Acceptance criteria
- [x] User should be shown a message stating no result found
- [x] The message is correctly styled in keeping with the website
- [x] Users can see an option to add in a new entry once logged in
- [x] Users not logged in are shown error message and directed to log in
- [x] Logged in user are redirected to the correct page
