### ISSUE TITLE
Link to Wifi Location page

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#26]
As a user, I can click on any listed WIFI location to view a detailed page about that location, so that I can get more information about the WIFI spot.

### Task
- [x] Create a page for each WIFI location
- [x] Link WIFI location page to the correct WIFI location listing
- [x] Create a hover effect for the link
- [x] Style the link in keeping with the website
- [x] WIFI location page should link to database to return correct data
- [x] Create back button

### Acceptance criteria
- [x] When a user clicks on a WIFI location link they are taken to the correct page
- [x] The WIFI location list has the correct link styling
- [x] The link text is clear and obvious to the user what happens when they click the button
- [x] The WIFI location page displays the relevant information 
- [x] User can go back to main search page using the button
