### ISSUE TITLE
On Screen Message

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#30]
As a user, I can see the correct on-screen message when logging in and out so that it is clear what state I am in.

### Task
- [x] Create pop-up messages for login and logout actions.
- [x] Link pop-up messages to login and logout events.
- [ ] Track user status to determine login/logout state.

### Acceptance criteria
- [ ] On-screen messages display correctly when the user logs in or out.
- [x] The messages indicate the user's current state (logged in or out).
- [x] The pop-up messages include a close button and darken the background.
