### ISSUE TITLE
Locate Wifi Locations

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#33]
As a logged-in user, I can locate the wifi location creation form through either the navigation bar or search feature so that I can create a new wifi location on the website.

### Task
- [x] Create a navigation bar link to the wifi location creation form.
- [ ] Create an on-screen link to the wifi location creation form.
- [x] Style the navigation bar and on-screen links in keeping with the website.

### Acceptance criteria
- [x] The user can access the wifi location creation form through the navigation bar or search feature.
- [x] The links are styled consistently with the website
