### ISSUE TITLE
WIFI Location view full details

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#42]
As a user, I can click on a WIFI location link from the search results so that I am taken to a dedicated page with full details about the WIFI spot.

### Task
- [x] Create clickable links on search results for each wifi location
- [x] Ensure link navigates to the correct WIFI spot details page
- [ ] Style link to match the website's design

### Acceptance criteria
- [x] Clicking on the link takes you to the correct WIFI location page
- [ ] Link is styled correctly according to the website's design standards
