### ISSUE TITLE
WIFI Location layout

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#43]
As a user, I can see that all WIFI Location pages have the same layout so that it makes it easier to navigate and find information quickly.

### Task
- [ ] Create a generic layout template for WIFI Location pages
- [ ] Apply the generic layout to all WIFI Location pages
- [ ] Create consistent styling rules to apply to all WIFI Location pages
- [ ] Place the different sections of the WIFI page such as address details, amenities, WIFI signal information, and comments in a uniform location

### Acceptance criteria
- [ ] All WIFI Location pages follow the same layout template
- [ ] There should be consistent styling to all the WIFI Location pages
- [ ] The layout is responsive and displays the information correctly on different devices 
- [ ] Different sections of the page are consistently positioned regardless of the WIFI location
- [x] Users can navigate and find information quickly due to the uniform layout
