### ISSUE TITLE
Amenities Key

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#45]
As a user, I can refer to a key on the page so that I am able to determine what each amenities icon means.

### Task
- [ ] Create amenities key button
- [ ] Create system to display key on button press
- [ ] Create system to close key when not required
- [ ] Style key table 
- [ ] Write explanation for each key

### Acceptance criteria
- [ ] When clicking on the button the keys list should appear
- [ ] When clicking on the cross when the keys list is open should close the list
- [ ] The keys list should have the correct styling for the website
- [ ] The key list should clearly describe what each key means
