### ISSUE TITLE
Leave a Comment

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#47]
As a logged-in user, I can leave comments about the WIFI location so that I can leave a more descriptive review of the place.

### Task
- [x] Create a system check to verify if the user is logged in
- [x] Create a form for adding comments
- [ ] Create a submit button for the comment form
- [ ] Add validation to ensure the form is completed correctly before submission
- [x] Create and add a popup confirmation when a comment is submitted successfully

### Acceptance criteria
- [ ]  a user tries to add a comment a check is done to make sure that they are logged in, if they are not then they are prompted to do so. If they are logged in they are allowed to post a comment
- [ ] When posting a comment user should be able to enter text into the comment box and submit it
- [x] There should be a submit button below the comment box
- [ ] When a comment is successfully submitted a pop up will appear
- [ ] Validation checks have been added so the user can not submit an empty form
- [x] The comment is saved to the database and displayed on the wifi location page
