### ISSUE TITLE
WIFI Star Rating

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#48]
As a user, I can see a star rating on the WIFI spot page so that I can tell the quality of the WIFI signal in the WIFI location.

### Task
- [x] Create a star rating system using 5 star icons
- [ ] Star icons will update depending on the score the WIFI location has
- [ ] Database will store a value which is converted to give a rating out of 5 stars
- [ ] Stars to be displayed on the WIFI location page
- [ ] Stars are styled in keeping with the website

### Acceptance criteria
- [x] When a WIFI location page loads the star rating is visible on the page
- [x] The rating should show a score out of 5
- [ ] When a user adds a new rating for the WIFI location the overall rating is updated
- [ ] The star rating is correctly style in keeping with the website
