### ISSUE TITLE
Update Star Rating

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#49]
As a logged-in user, I can update the rating using a dropdown menu so that I can provide my feedback on how I found the quality of the WIFI signal.

### Task
- [ ] Create drop down menu for selection a rating
- [ ] Create submit button
- [ ] Creation function to update star rating when a new value is added
- [ ] Update database to store WIFI rating score
- [ ] Style rating system drop down
- [ ] Add validation to WIFI rating update system
- [ ] Create error message

### Acceptance criteria
- [ ] user is able to update the WIFI rating when they submit a new rating 
- [ ] rating updates in real time
- [ ] user can only submit a rating if the validation has passed
- [ ] correct error messages are shown
- [ ] Only logged-in users are able to see and interact with the rating update dropdown and submit button
- [ ] Correct styling is user in keeping with the website theme
