### ISSUE TITLE
View WIFI Location Image

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#50]
As a user, I can view an image related to the WIFI location on the page so that I can get a visual indication of what the location looks like so id recognise it if I go visit.

### Task
- [x] Ensure image is uploaded and stored in the database
- [x] Display image on the wifi location page when a user visits it
- [ ] Style image to match the website's design
- [x] Implement responsive design to ensure image dynamically adjust in size based on the screen size
- [x] Ensure image is loaded efficiently for better performance

### Acceptance criteria
- [x] The correct image is displayed when a user views a WIFI location page
- [ ] Image dynamically adjust in size according to the screen size (responsive design)
- [x] Image is styled consistently with the website’s overall design
- [x] Image loads quickly and efficiently without degrading page performance
