### ISSUE TITLE
Complete Search

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#52]
As a user, I can complete a search using a city or country name so that I can find Wi-Fi locations in that area.

### Task
- [ ] Create input search feature
- [ ] Create a search button
- [ ] Add in error handling
- [ ] Allow only text in input field
- [ ] Create no result response
- [ ] Design container for results and error
- [ ] Create function to search user input in database
- [ ] Add in validation

### Acceptance criteria
- [ ] Search feature only accepts text
- [ ] Any errors are displayed to the user under the search bar
- [ ] If the members search result can not be found, user is directed to create a new entry
- [ ] The search result should be styled and displayed in a user-friendly manner
- [ ] The user has the option to restart the search if they so which with ease
