### ISSUE TITLE
See Search Results

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#53]
As a user, I can see the results of the search I have completed so that I know which Wi-Fi spots are available in the specified country or city if any.

### Task
- [ ] Create a search button
- [x] Create one for each continent
- [ ] display results 
- [x] create uniform search results for city and country

### Acceptance criteria
- [ ] search feature works by user clicking a button
- [x] If the members search result cannot be found, user can create a new entry
- [ ] The search result should be styled and displayed in a user-friendly manner
- [x] The user has the option to restart the search if they so which with ease
