### ISSUE TITLE
List Result of search

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#54]
As a user, I can search a country and expect to see a list of cities within that country so that I can narrow down the results when I am searching for a specific city.

### Task
- [x] Create Button for Continent linked to Country
- [x] Create loading screen
- [x] Create Hover Effect for button

### Acceptance criteria
- [x] User should see 6 continent buttons
- [x] All Buttons correctly styled
- [x] Buttons take user to correct page
- [x] Loading indicators are shown while the search is in progress
