### ISSUE TITLE
Specific City WIFI Locations

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#55]
As a user, I can search for a city and expect to see a list of Wi-Fi locations within that city so that I can choose a specific spot.

### Task
- [ ] Capture user input from the search field
- [ ] Create validation to check field is not empty and contains only letters
- [ ] Design container for displaying results and error
- [ ] Create a function to search for Wi-Fi locations in the specified city from the database
- [ ] Display search results in a results container
- [ ] Display a message if no results are found for the search term
- [ ] Add error handling for API requests
- [ ] Display WIFI location results in a table filter format
- [ ] Create loading screen

### Acceptance criteria
- [ ] The search field should only accept letters
- [ ] If there is an error this should be shown below the search bar
- [ ] After the user searches a country if there is a result then all the WIFI locations in that city should be down below
- [ ] If there are no WIFI locations, then a message is displayed prompting the user to log in and add a new entry
- [ ] User can retry a search if the first fails
- [ ] Loading indicators are shown while the search is in progress
