### ISSUE TITLE
City and Country Standard format

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#56]
As a user, I can view the profile pages for cities and countries in a standard format so that I get an overview of available WiFi locations and other relevant information in an easy to follow format.

### Task
- [ ] Create a template for city and countries
- [ ] Template must contain city or country name, and number of wifi locations in that search result
- [ ] Display list of results in a table format 
- [ ] Style result in keeping with the website
- [ ] Create links which display on the end of each search result

### Acceptance criteria
- [x] Search results are shown in a uniform manner to improve usability 
- [ ] Each result should have a link so the user can continue to refine their search
- [x] Results are correctly styled
