### ISSUE TITLE
Search Submission No Result Prompt

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#57]
As a user, I can expect to receive a prompted after submitting a search and getting no results so that I am aware of this and the fact that I can submit a new entry once logged in so that the database can be updated with more information.

### Task
- [ ] Create on screen error message
- [ ] Create link to wifi location creation form
- [ ] Create check to see if user is logged in
- [ ] Create link  to form for a new entry
- [ ] Create confirmation new entry added
- [ ] Redirect non logged in users who try to create a new wifi location to the log in screen
- [ ] Style all sections in keeping with the website

### Acceptance criteria
- [ ] When user enters and gets no result an error should appear
- [ ] User should be able to see a link promote to creating a new entry
- [ ] Before creating a new entry a check is carried out to determine if the user is logged in
- [ ] Logged in users will see the wifi location creation form
- [ ] Non logged in users will see the log in screen
