### ISSUE TITLE
Navigate between country and city

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#58]
As a user, I can easily navigate between country and city search results so that I can refine my search without starting over.

### Task

- [x] Create breadcrumb will current URL path
- [x] Style breadcrumb

### Acceptance criteria
- [x] When clicking the button the user is reverted back to the correct page
- [x] The breadcrumb updates depending on the location of the user in the website
