### ISSUE TITLE
Loading Indicator 

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#59]
As a user, I can see loading indicators when searching or filtering results so that I know the system is processing my request.

### Task
- [ ] Create a loading component
- [ ] Loading component to contain a gif of loading circle
- [ ] Component should be modular and reusable 
- [ ] Style loading indicator in keeping with the website
- [ ] Creation function to link loader to submission of search

### Acceptance criteria
- [x] Loading indicator works on multiple pages
- [ ] Indicator is correctly styled
- [ ] The indicator only appears after a user has submitted a search request
- [x] Loading indicator is modular and reusable
