### ISSUE TITLE
Clear and Helpful error messages 

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#60]
As a user I can receive clear and helpful error messages so that I am able to see when something has gone wrong

### Task
- [x] Create custom popup messages for errors
- [x] Create custom error messages for different errors
- [x] Include html validation in forms
- [x] Include error handling in JavaScript code
- [x] Include error handling in python code

### Acceptance criteria
- [x] A popup message appears when an error errors
- [x] There should be custom messages depending on the error
- [x] Html validation should be included on all forms and fields
- [x] Error handling is included in the javascript code – try/catch
- [x] Error handling is included in the python code 
- [x] Error message is clear and helpful to read and understand
- [x] Error message is accurate
