### ISSUE TITLE
Stop Errors Occuring

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#61]
As a developer I can stop errors from occurring so that the user experience is not impacted

### Task
- [x] Complete unittest on python code
- [x] Complete jest testing on JavaScript code
- [x] Complete manual testing of code

### Acceptance criteria
- [x] Unit test is completed on all python code
- [x] Jest test is completed on all JavaScript code
- [x] Manual testing carried out on completed project
- [x] Code is error free
- [x] Any errors found are logged
