### ISSUE TITLE
Error Catching

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#62]
As a developer I can implement error catching so that the I can understand where the error is coming from and fix it

### Task
- [ ] Use try catch in JavaScript code
- [ ] Use try expect in python code
- [ ] Include console log when creating site and remove from final production

### Acceptance criteria
- [ ] Try-catch is used in JavaScript code
- [ ] Try expect used in python code
- [ ] Console log is used when testing sections of code
- [ ] Console log and commented out code removed from final product
- [ ] Errors are caught and fixed, if not logged to be resolved
