### ISSUE TITLE
Incorrect URL

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#63]
As a user I can expect to be shown a message if an incorrect URL is inputted so that I can tell when an error has occurred and what to do

### Task
- [x] Create 404 error page
- [x] Link 404 page in the URL's
- [x] Write custom error page content describing error

### Acceptance criteria
- [x] 404 page is created
- [x] 404 page is displayed when incorrect URL inputted
- [x] 404 page contains custom error message
- [x] Page contains home button to take user back to the site
