### ISSUE TITLE
Consistent Error Message Format

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#64]
As a user I can expect consistent error message format and style so that I can easily understand and notice errors

### Task
- [x] create a style and format standard for all messages
- [x] create CSS style to match design plan
- [x] apply correct styling to the different error messages
- [x] use clear and concise language

### Acceptance criteria
- [x] System displays error messages using the correct style
- [x] System has defined style and format standard
- [x] The wireframe design plan can be seen to have been followed
- [x] Errors have clear language
- [x] Clear for a user to see the difference between error message and a normal message
