### ISSUE TITLE
Restricted access to certain sections 

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#65]
As a developer I can stop users from accessing sections of the website without correct authority so that the site is kept secure

### Task
- [x] User specific sections to be contained within conditional functions
- [x] User access checked when logged in – role base access
- [x] User specific sections not shown when webpage loads

### Acceptance criteria
- [x] Code is added to check users account on sign in
- [x] Conditional functions use values from user database to check what can be shown
- [x] Website does not display user-specific sections when website loads
- [x] When user logs out, webpage reverts to initial state and removes user specific information and links
