### ISSUE TITLE
Test Forms and Fields

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#69]
As a developer I can test all forms and fields a user has to complete so that I can make sure the correct information is stored and the user has a good experience

### Task
- [x] Test all forms work correctly.
- [x] Test form fields they accept correct data and data format.
- [x] Test form validation.
- [x] Test error handling.
- [x] Test submit a form to check the form content.
- [x] form should reset are being completed.

### Acceptance criteria
- [x] Form fields tested to check validation works.
- [x] Form and form fields checked to make they work correctly.
- [x] Form fields data type checked to only allow certain data type.
- [x] Check form can be submitted correctly.
- [x] Check user gets correct error message if there is an error with the form.
- [x] Check form meets accessibility guidelines. 
- [x] Form is responsive.
