### ISSUE TITLE
Unittest Code

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#71]
As a developer I can pass the python code through unittest so that I can thoroughly check the code has no errors and meets all python standards

### Task
- [ ] Write unit tests for all functions in the code
- [ ] Import unittest
- [ ] Make sure tests cover function usage.
- [ ] Create mock objects to test user account.
- [x] Create mock object to test form submission.
- [ ] Create mock data to test clan page creation.
- [x] Log test results in readme.

### Acceptance criteria
- [x] Unit tests are created for all functions to check they work as expected.
- [ ] Python code checked that it meets python standards.
- [x] Tests cover all possible function usage and scenarios including obscure one.
- [ ] Mock data is used to test functions against database.
- [x] All results are logged in a readme file.
- [x] Tests are written in a clean and concise way to test different functions.
