### ISSUE TITLE
Validate CSS

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#73]
As a developer I can use a validator on the CSS code so that I can thoroughly check the code has no errors and meets all standards.

### Task
- [x] Correct any errors shown in validator.
- [x] Pass the CSS against the CSS validator.
- [x] Correct any errors found in validator.
- [x] Document results of html and CSS validator.

### Acceptance criteria
- [x] CSS is checked against validator. 
- [x] Any errors found are corrected.
- [x] Results of the tests are well documented in Readme. 
- [x] Sematic html is correctly used.
