### ISSUE TITLE
WIFI Location View - Google Map

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#75]
As a user, I can view a map on the Wi-Fi Location page showing the exact location and nearby amenities, so that I can better understand the area around the Wi-Fi spot.

### Task
- [ ] Integrate Google Maps API into the Wi-Fi spot page.
- [ ] Display the Wi-Fi spot's exact location on the map.
- [ ] Create function to get wifi location and pass the data to google maps API
- [ ] Style the map to fit the website's design.

### Acceptance criteria
- [ ] The map is visible on the Wi-Fi spot page.
- [ ] The Wi-Fi location is centre of the image.
- [ ] Nearby amenities are shown on the map.
- [ ] The map is styled consistently with the website’s theme.
