### ISSUE TITLE
Transport Options

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#77]
As a user, I can see nearby public transportation options and routes to the Wi-Fi Location, so that I can plan my trip effectively.

### Task
- [ ] Add in a public transport API to fetch nearby transport options.
- [ ] Display nearby public transit stops and routes on the Wi-Fi spot page.
- [ ] Include route information to the WiFi Location from any selected transport stop.
- [ ] Style the transport information to fit the website's overall design.

### Acceptance criteria
- [ ] Public transport options are visible on the WiFi Location page.
- [ ] Transport routes to the Wi-Fi spot are displayed clearly.
- [ ] The information is accurate and updates as per real-time data.
- [ ] The transport information is styled in alignment with the website’s theme.
