### ISSUE TITLE
Save WIFI Location to Possibles

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#80]
As a user, I can save a Wi-Fi location to my Possibles so that I can remember to visit it later.

### Task
- [x] Create a database for Possibles linked to User and Wi-Fi Location.
- [x] Create a frontend interface to add locations to the Possibles.
- [x] Create a backend endpoint to handle new wifi locations being added.
- [x] Implement validation to ensure the same location isn’t added twice.
- [x] Style page in keeping with website

### Acceptance criteria
- [x] Users can add Wi-Fi locations to their Possibles.
- [x] The Possibles is linked to the user’s account and shown as a navbar tab.
- [x] Duplicate entries are flagged as an error and not added.
- [x] A confirmation message appears when a WIFI location has been added successfully.
- [x] Correct styling is used
