### ISSUE TITLE
Set Visit Status - "Possibles"

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#82]
As a user, I can mark Wi-Fi locations in my Possibles as "Planned" or "Visited" so that I can track which locations I’ve already visited and which I plan to visit.

### Task
- [ ] Add a status field to the Possibles model.
- [ ] Implement front end controls for setting the status.
- [ ] Update the backend to handle status changes.
- [ ] Display status indicators in the Possibles view.

### Acceptance criteria
- [ ] Users can set and update the status for each Possibles item.
- [ ] Status is clearly displayed in the Possibles.
- [ ] The status will display based on the saved code in the database.
- [ ] A confirmation message appears when the status is updated.
