### ISSUE TITLE
Add Notes - "Possibles" 

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#83]
As a user, I can add personal notes to each Wi-Fi location in my Possibles so that I can remember specific details or reasons for wanting to visit.

### Task
- [ ] Add a notes field to the Possibles model.
- [ ] Add a UI for entering and editing notes.
- [ ] Ensure notes are saved and retrieved correctly.
- [ ] Display notes in the Possibles page.
- [ ] Limit length of notes

### Acceptance criteria
- [ ] Users can add, edit, and view notes for each Possibles item.
- [ ] Notes are saved and displayed correctly.
- [ ] Notes will have a max limit.
- [ ] A confirmation message appears when notes are saved.
