### ISSUE TITLE
Prioritise Possibles Items

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#84]
As a user, I can assign a priority level to each Wi-Fi location in my Possibles so that I can organize my list by importance 

### Task
- [ ] Add a priority field to the Wishlist model.
- [ ] Add UI controls for setting priority levels.
- [ ] Sort the Possibles by priority.
- [ ] Display priority value clearing next to each WIFI location in the Possibles 

### Acceptance criteria
- [ ] Users can set and update priority levels for each item.
- [ ] The Possibles are sortable by the priority value.
- [ ] Priority levels are clearly displayed.
- [ ] Changes in priority are updated in the database across sessions.
