### ISSUE TITLE
Lighthouse Testing

### ISSUE THREAD

**Issue by GMontaque** [GMontaque/wifi-wander#85]
As a developer I can use lighthouse to test the website so that I can check the performance, accessibility, SEO and best practices up to the standard required.

### Task
- [x] Run lighthouse in the chrome browser.
- [x] Record the results.
- [x] Run lighthouse on pagespeed insights.
- [x] record the results.
- [x] update and correct code as per lighthouse results.

### Acceptance criteria
- [x] Lighthouse is used to test website for performance, accessibility, SEO, and best practices.
- [x] The results of the Lighthouse test are recorded in the readme.
- [x] PageSpeed Insights is used to test website for performance, accessibility, SEO, and best practices.
- [x] The results of the PageSpeed Insights test are recorded in the readme.
- [x] Code is updated and correct code as per Lighthouse and PageSpeed Insights results.
